// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProfile(arg1) {
  return window['go']['main']['App']['AddProfile'](arg1);
}

export function CancelDiagnostics() {
  return window['go']['main']['App']['CancelDiagnostics']();
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DisableAdapter(arg1) {
  return window['go']['main']['App']['DisableAdapter'](arg1);
}

export function EnableAdapter(arg1) {
  return window['go']['main']['App']['EnableAdapter'](arg1);
}

export function GetAdapters() {
  return window['go']['main']['App']['GetAdapters']();
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function IsElevated() {
  return window['go']['main']['App']['IsElevated']();
}

export function OpenProfileFolder() {
  return window['go']['main']['App']['OpenProfileFolder']();
}

export function PingHost(arg1, arg2) {
  return window['go']['main']['App']['PingHost'](arg1, arg2);
}

export function QuickCheck(arg1, arg2) {
  return window['go']['main']['App']['QuickCheck'](arg1, arg2);
}

export function SetDHCP(arg1) {
  return window['go']['main']['App']['SetDHCP'](arg1);
}

export function SetStaticIP(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetStaticIP'](arg1, arg2, arg3, arg4, arg5);
}

export function TraceRouteHost(arg1) {
  return window['go']['main']['App']['TraceRouteHost'](arg1);
}

export function UpdateProfile(arg1) {
  return window['go']['main']['App']['UpdateProfile'](arg1);
}
