// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {profile} from '../models';
import {network} from '../models';
import {diagnostics} from '../models';

export function AddProfile(arg1:profile.IPProfile):Promise<void>;

export function CancelDiagnostics():Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DisableAdapter(arg1:string):Promise<void>;

export function EnableAdapter(arg1:string):Promise<void>;

export function GetAdapters():Promise<Array<network.Adapter>>;

export function GetProfiles():Promise<Array<profile.IPProfile>>;

export function IsElevated():Promise<boolean>;

export function OpenProfileFolder():Promise<void>;

export function PingHost(arg1:string,arg2:number):Promise<string>;

export function QuickCheck(arg1:string,arg2:boolean):Promise<diagnostics.QuickCheckResult>;

export function SetDHCP(arg1:string):Promise<void>;

export function SetStaticIP(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function TraceRouteHost(arg1:string):Promise<string>;

export function UpdateProfile(arg1:profile.IPProfile):Promise<void>;
